#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

HOUR=0
while [ "$HOUR" -lt 13 ]; do
    echo "Hour: $HOUR"
    M=1
    while [ $M -lt 60 ]; do
	echo "$M"
	((M++))
    done
    ((HOUR++))
done